-------SPITAL------

CREATE TABLE SPITAL(COD_SPITAL INT IDENTITY(1,1) CONSTRAINT PKEY_SPITAL PRIMARY KEY,
					DENUMIRE VARCHAR(100) CONSTRAINT DENUMIRE_SPITAL NOT NULL,
					ADRESA VARCHAR(100) CONSTRAINT ADRESA_SPITAL NOT NULL,
					TELEFON VARCHAR(20) CONSTRAINT TELEFON_SPITAL NOT NULL,
					MAIL VARCHAR(50) UNIQUE,
					COD_POSTAL VARCHAR(6)
					);

INSERT INTO SPITAL 
VALUES('Spitalul Universitar de Urgente Bucuresti', 'St. Splaiul independentei nr.169', '021-318-0523', 'universitarurgente@gamil.com', '210728')

INSERT INTO SPITAL 
VALUES('Spitalul Clinic CF2 Bucuresti', 'Bd. Marasesti nr. 63', '037-229-8711', 'clinicurgentecf@gamil.com', '284928')


INSERT INTO SPITAL 
VALUES('Spitalul CF Witting', 'St. Calea Plevei nr. 142-144', '021-317-0068', 'secretariat@spitalcfwiting.com', '284263')

INSERT INTO SPITAL 
VALUES('Spitalul Universitar de Urgenta Elias', 'Bd. Marasti nr. 17', '021-312-0465', 'spital@elias.com', '837239')

INSERT INTO SPITAL 
VALUES('Spitalul Clinic Coltea', 'Bd. Ion C. Bratianu nr. 17', '031-333-2873', 'urgente@coltea.com', '906232')

SELECT * FROM SPITAL


--------CENTRU DE DONARE-------


CREATE TABLE CENTRU_DONARE(COD_CENTRU INT IDENTITY(1,1) CONSTRAINT PKEY_CENTRU PRIMARY KEY,
					DENUMIRE VARCHAR(100) CONSTRAINT DENUMIRE_CENTRU NOT NULL,
					DATA_INSCRIERII DATE CONSTRAINT DATA_INSCRIERII NOT NULL,
					COD_SPITAL INT, CONSTRAINT FK_CENTRU FOREIGN KEY(COD_SPITAL) REFERENCES SPITAL(COD_SPITAL));


SELECT * FROM CENTRU_DONARE

INSERT INTO CENTRU_DONARE
VALUES('CDSUUB','2010-02-07',1)

INSERT INTO CENTRU_DONARE
VALUES('CDSCCB','2007-04-17',2)

INSERT INTO CENTRU_DONARE
VALUES('CDSCW','2011-05-27',3)

INSERT INTO CENTRU_DONARE
VALUES('CDSUUE','2010-02-15',4)

INSERT INTO CENTRU_DONARE
VALUES('CDSCC','2004-12-01',5)

SELECT * FROM CENTRU_DONARE


------DEPARTAMENT----
CREATE TABLE DEPARTAMENT(COD_DEPARTAMENT INT IDENTITY(1,1) CONSTRAINT PKEY_DEPARTAMENT PRIMARY KEY,
					DENUMIRE VARCHAR(100) CONSTRAINT DENUMIRE_DEPARTAMENT NOT NULL,
					COD_SPITAL INT, CONSTRAINT FK_DEPARTAMENT FOREIGN KEY(COD_SPITAL) REFERENCES SPITAL(COD_SPITAL));

SELECT * FROM DEPARTAMENT

INSERT INTO DEPARTAMENT
VALUES('URGENTE',1)

INSERT INTO DEPARTAMENT
VALUES('ATI',1)

INSERT INTO DEPARTAMENT
VALUES('CHIRURGIE GENERALA',1)

INSERT INTO DEPARTAMENT
VALUES('MEDICINA INTERNA',2)

INSERT INTO DEPARTAMENT
VALUES('MEDICINA LEGALA',2)

INSERT INTO DEPARTAMENT
VALUES('MEDICINA PRIMARA',2)

-----SECTIE----
CREATE TABLE SECTIE(COD_SECTIE INT IDENTITY(1,1) CONSTRAINT PKEY_SECTIE PRIMARY KEY,
					DENUMIRE VARCHAR(100) CONSTRAINT DENUMIRE_SECTIE NOT NULL,
					COD_DEPARTAMENT INT, CONSTRAINT FK_SECTIE FOREIGN KEY(COD_DEPARTAMENT) REFERENCES DEPARTAMENT(COD_DEPARTAMENT));

SELECT * FROM SECTIE

INSERT INTO SECTIE
VALUES('GASTROLOGIE',1)

INSERT INTO SECTIE
VALUES('UROLOGIE',1)

INSERT INTO SECTIE
VALUES('CARDIOLOGIE',1)

INSERT INTO SECTIE
VALUES('GINECOLOGIE',2)

INSERT INTO SECTIE
VALUES('ORTOPEDIE',3)

INSERT INTO SECTIE
VALUES('PEDIATRIE',3)


-----ETIOLOGIE----
CREATE TABLE ETIOLOGIE(COD_ETIOLOGIE INT IDENTITY(1,1) CONSTRAINT PKEY_ETIOLOGIE PRIMARY KEY,
					DENUMIRE VARCHAR(100) CONSTRAINT DENUMIRE_ETIOLOGIE NOT NULL,
					COD_SECTIE INT, CONSTRAINT FK_ETIOLOGIE FOREIGN KEY(COD_SECTIE) REFERENCES SECTIE(COD_SECTIE));

SELECT * FROM ETIOLOGIE

INSERT INTO ETIOLOGIE
VALUES('TOXICA',1)

INSERT INTO ETIOLOGIE
VALUES('CONGENITALA',1)

INSERT INTO ETIOLOGIE
VALUES('ISCHEMICA',1)

INSERT INTO ETIOLOGIE
VALUES('INFECTIOASA',2)

INSERT INTO ETIOLOGIE
VALUES('RENALA',2)

INSERT INTO ETIOLOGIE
VALUES('ETIOLOGIE GENETICA',2)

INSERT INTO ETIOLOGIE
VALUES('IDIOPATICA',3)


----PACIENT----
CREATE TABLE PACIENT(COD_PACIENT INT IDENTITY(1,1) CONSTRAINT PKEY_PACIENT PRIMARY KEY,
					NUME VARCHAR(100) CONSTRAINT NUME_PACIENT NOT NULL,
					PRENUME VARCHAR(100) CONSTRAINT PRENUME_PACIENT NOT NULL,
					DATA_NASTERII DATE CONSTRAINT DATA_NASTERII NOT NULL,
					SEX VARCHAR(10) CONSTRAINT SEX_PACIENT NOT NULL,
					TELEFON VARCHAR(20) CONSTRAINT TELEFON_PACIENT NOT NULL,
					MAIL VARCHAR(50) UNIQUE,
					COD_CENTRU INT, CONSTRAINT FK_PACIENT FOREIGN KEY(COD_CENTRU) REFERENCES CENTRU_DONARE(COD_CENTRU));

   

INSERT INTO PACIENT
VALUES('POPESCU', 'IRINA', '1993-04-24','F','0745-263-972','popescuirina@yahoo.com',1)

INSERT INTO PACIENT
VALUES('IONESCU', 'MIHAI', '1989-11-25','M','0765-433-823','ionescumihai25@gmail.com',1)

INSERT INTO PACIENT
VALUES('DUMITRESCU', 'DAN', '1997-11-08','M','0734-435-893','dandumitrescu8@yahoo.com',null)

INSERT INTO PACIENT
VALUES('CONSTANTINESCU', 'LUMINITA', '2000-12-24','F','0775-678-543','cntlumy@yahoo.com',1)

INSERT INTO PACIENT
VALUES('IROD', 'ANDREEA', '1987-09-21','F','0744-098-322','andreeairod@gmail.com',1)

INSERT INTO PACIENT
VALUES('MARCU', 'ELY', '1984-09-21','F','0789-536-645','marcuely@gmail.com',1)

INSERT INTO PACIENT
VALUES('PATRASCU', 'CLAUDIU', '1967-02-25','M','0795-543-657','claupatrascu@gmail.com',null)

INSERT INTO PACIENT
VALUES('RUS', 'ALIN', '1945-03-08','M','0754-523-535','alinrus8@yahoo.com',null)

INSERT INTO PACIENT
VALUES('EFTENIE', 'ROBERTA', '1987-11-23','F','0744-235-345','robyeftenoiu@yahoo.com',null)

INSERT INTO PACIENT
VALUES('IFTIM', 'ANDREEA', '1998-04-21','F','0735-454-322','iftimandreea21@gmail.com',1)

SELECT * FROM PACIENT

------FISA MEDICALA------
CREATE TABLE FISA_MEDICALA(COD_PACIENT INT CONSTRAINT PK_REPARTIZARE_PACIENT REFERENCES PACIENT(COD_PACIENT),
					DATA_INTEMEIERII DATE CONSTRAINT DATA_INTEMEIRII NOT NULL,
					COD_ETIOLOGIE INT CONSTRAINT PK_REPARTIZARE_ETIOLOGIE REFERENCES ETIOLOGIE(COD_ETIOLOGIE),
					CONSTRAINT PK_REPARTIZARE PRIMARY KEY(COD_PACIENT, COD_ETIOLOGIE));

SELECT * FROM FISA_MEDICALA

INSERT INTO FISA_MEDICALA
VALUES(1,'2007-02-07',1)

INSERT INTO FISA_MEDICALA
VALUES(2,'2009-10-10',2)

INSERT INTO FISA_MEDICALA
VALUES(3,'2015-06-01',1)

INSERT INTO FISA_MEDICALA
VALUES(4,'2011-11-11',4)

INSERT INTO FISA_MEDICALA
VALUES(5,'2013-01-12',4)

INSERT INTO FISA_MEDICALA
VALUES(6,'2010-11-17',5)

INSERT INTO FISA_MEDICALA
VALUES(7,'2006-04-19',4)

INSERT INTO FISA_MEDICALA
VALUES(8,'2002-08-22',3)

INSERT INTO FISA_MEDICALA
VALUES(9,'2009-09-16',4)

INSERT INTO FISA_MEDICALA
VALUES(10,'2013-12-07',5)

-----DOCTOR----
CREATE TABLE DOCTOR(COD_DOCTOR INT IDENTITY(1,1) CONSTRAINT PKEY_DOCTOR PRIMARY KEY,
					NUME VARCHAR(100) CONSTRAINT NUME_DOCTOR NOT NULL,
					PRENUME VARCHAR(100) CONSTRAINT PRENUME_DOCTOR NOT NULL,
					DATA_NASTERII DATE CONSTRAINT DATA_NASTERII NOT NULL,
					TELEFON VARCHAR(20) CONSTRAINT TELEFON_DOCTOR NOT NULL,
					MAIL VARCHAR(50) UNIQUE);

 SELECT * FROM DOCTOR

INSERT INTO DOCTOR
VALUES('MARTIN', 'ILEANA', '1997-07-09','0767-263-342','martinileana@yahoo.com')

INSERT INTO DOCTOR
VALUES('DIACONESCU', 'MIHAI', '1992-06-20','0732-453-535','diaconescumihai@gmail.com')

INSERT INTO DOCTOR
VALUES('GHEORGHE', 'DAN', '1980-12-08','0738-435-345','dangh1980@yahoo.com')

INSERT INTO DOCTOR
VALUES('IROD', 'ANA', '1991-07-14','0723-345-435','annairod@yahoo.com')

INSERT INTO DOCTOR
VALUES('TELEMAN', 'DENIS', '1978-11-01','0790-453-425','denisstl@gmail.com')

INSERT INTO DOCTOR
VALUES('ISTRATE', 'MARIA', '1990-03-11','0744-567-423','mariaistrate@gmail.com')

SELECT * FROM DOCTOR


------CONTRACT----

CREATE TABLE CONTRACT(COD_SPITAL INT CONSTRAINT PK_CONTRACT_FACULTATE REFERENCES SPITAL(COD_SPITAL),
					DATA_INCEPUT DATE CONSTRAINT DATA_INCEPUT NOT NULL,
					COD_DOCTOR INT CONSTRAINT PK_CONTRACT_DOCTOR REFERENCES DOCTOR(COD_DOCTOR),
					SALARIU INT CONSTRAINT SALARIU_CONTRACT NOT NULL,
					CONSTRAINT PK_CONTRACT PRIMARY KEY(COD_SPITAL, COD_DOCTOR));
SELECT * FROM CONTRACT

INSERT INTO CONTRACT
VALUES (1,'1990-12-12',1,5000)

INSERT INTO CONTRACT
VALUES (2,'1989-02-22',2,6453)

INSERT INTO CONTRACT
VALUES (3,'1978-01-29',1,7387)

INSERT INTO CONTRACT
VALUES (1,'1970-03-31',3,5624)

INSERT INTO CONTRACT
VALUES (1,'1977-07-19',4,8763)

INSERT INTO CONTRACT
VALUES (1,'1970-03-31',5,5624)

INSERT INTO CONTRACT
VALUES (1,'1977-07-19',6,8763)


-----SALON-----
CREATE TABLE SALON(COD_SALON INT IDENTITY(1,1) CONSTRAINT PKEY_SALON PRIMARY KEY,
					DENUMIRE VARCHAR(100) CONSTRAINT DENUMIRE_SALON NOT NULL,
					LOCATIE VARCHAR(100) CONSTRAINT LOCATIE_SALON NOT NULL);

SELECT * FROM SALON

INSERT INTO SALON
VALUES ('212','ETAJ 2')

INSERT INTO SALON
VALUES ('172','ETAJ 1')

INSERT INTO SALON
VALUES ('021','PARTER')

INSERT INTO SALON
VALUES ('567','ETAJ 5')

INSERT INTO SALON
VALUES ('722','ETAJ 7')

INSERT INTO SALON
VALUES ('281-B','ETAJ 2, ARIPA B')

INSERT INTO SALON
VALUES ('562-A','ETAJ 5, ARIPA A')


----------EVOLUTIE_PACIENT---------
CREATE TABLE EVOLUTIE_PACIENT(COD_EVOLUTIE INT IDENTITY(1,1) CONSTRAINT PKEY_EVOLUTIE PRIMARY KEY,
					DENUMIRE VARCHAR(100) CONSTRAINT DENUMIRE_STARE NOT NULL);

SELECT * FROM EVOLUTIE_PACIENT

INSERT INTO EVOLUTIE_PACIENT
VALUES('BUNA');

INSERT INTO EVOLUTIE_PACIENT
VALUES('LA FEL');

INSERT INTO EVOLUTIE_PACIENT
VALUES('REA');


--------ANALIZE--------
CREATE TABLE ANALIZE(COD_ANALIZE INT IDENTITY(1,1) CONSTRAINT PKEY_ANALIZE PRIMARY KEY,
					FORMA VARCHAR(100) CONSTRAINT FORMA_ANALIZE NOT NULL,
					COD_EVOLUTIE INT, CONSTRAINT FK_ANALIZE FOREIGN KEY(COD_EVOLUTIE) REFERENCES EVOLUTIE_PACIENT(COD_EVOLUTIE));

SELECT * FROM ANALIZE

INSERT INTO ANALIZE
VALUES('SANGE',1);

INSERT INTO ANALIZE
VALUES('URINA',2);

INSERT INTO ANALIZE
VALUES('SALIVA',3);


------DIAGNOSTIC-----
CREATE TABLE DIAGNOSTIC(PROCENT INT CONSTRAINT PROCENT_ANALIZA NOT NULL,
						COD_PACIENT INT CONSTRAINT PK_PACIENT REFERENCES PACIENT(COD_PACIENT),
						COD_ANALIZE INT CONSTRAINT PK_ANALIZE REFERENCES ANALIZE(COD_ANALIZE),
						CONSTRAINT PK_DIAGNOSTIC PRIMARY KEY(COD_PACIENT, COD_ANALIZE));

SELECT * FROM DIAGNOSTIC

INSERT INTO DIAGNOSTIC
VALUES(90,1,1);

INSERT INTO DIAGNOSTIC
VALUES(80,1,2);

INSERT INTO DIAGNOSTIC
VALUES(60,1,3);

INSERT INTO DIAGNOSTIC
VALUES(45,2,1);

INSERT INTO DIAGNOSTIC
VALUES(70,2,2);

INSERT INTO DIAGNOSTIC
VALUES(82,3,1);

INSERT INTO DIAGNOSTIC
VALUES(93,3,3);

INSERT INTO DIAGNOSTIC
VALUES(54,4,1);

INSERT INTO DIAGNOSTIC
VALUES(88,5,2);

INSERT INTO DIAGNOSTIC
VALUES(39,6,2);

INSERT INTO DIAGNOSTIC
VALUES(32,7,1);

INSERT INTO DIAGNOSTIC
VALUES(59,8,1);

INSERT INTO DIAGNOSTIC
VALUES(88,9,1);

INSERT INTO DIAGNOSTIC
VALUES(89,10,1);

INSERT INTO DIAGNOSTIC
VALUES(49,10,3);

INSERT INTO DIAGNOSTIC
VALUES(78,8,2);

INSERT INTO DIAGNOSTIC
VALUES(90,5,1);


------DESFASURATOR-----
CREATE TABLE DESFASURATOR(COD_ETIOLOGIE INT CONSTRAINT PK_ETI_DESFASURATOR REFERENCES ETIOLOGIE(COD_ETIOLOGIE),
						COD_EVOLUTIE INT CONSTRAINT PK_EV_DESFASURATOR REFERENCES EVOLUTIE_PACIENT(COD_EVOLUTIE),
						COD_DOCTOR INT CONSTRAINT PK_DOC_DESFASURATOR REFERENCES DOCTOR(COD_DOCTOR),
						COD_SALON INT CONSTRAINT PK_SALON_DESFASURATOR REFERENCES SALON(COD_SALON),
						CONSTRAINT PK_DESFASURATOR PRIMARY KEY(COD_ETIOLOGIE, COD_EVOLUTIE, COD_DOCTOR, COD_SALON));

SELECT * FROM DESFASURATOR

INSERT INTO DESFASURATOR
VALUES(1,1,1,1)

INSERT INTO DESFASURATOR
VALUES(2,2,2,2)

INSERT INTO DESFASURATOR
VALUES(3,3,3,3)

INSERT INTO DESFASURATOR
VALUES(4,2,4,4)

INSERT INTO DESFASURATOR
VALUES(5,1,5,5)

INSERT INTO DESFASURATOR
VALUES(6,3,6,6)

INSERT INTO DESFASURATOR
VALUES(7,2,1,1)

select * from PACIENT